config/routes.rb
Rails.application.routes.draw do
  resources :gastos
  resources :tipogastos

  #resources :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get  '/importfile', to: 'gastos#importfile'
  post '/importfile', to: 'gastos#importfile'

  get  '/classificar', to: 'gastos#classificar'
  post '/classificar', to: 'gastos#classificar'

  get  '/consultames', to: 'gastos#consultames'
  post '/consultames', to: 'gastos#consultames'

  get  '/updateclassificar', to: 'gastos#updateclassificar'
  post '/updateclassificar', to: 'gastos#updateclassificar'
  patch '/updateclassificar', to: 'gastos#updateclassificar'


  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gasto.rb
class Gasto < ApplicationRecord
  belongs_to :tipogasto
end

app/models/tipogasto.rb
class Tipogasto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gastos_controller.rb
class GastosController < ApplicationController
  before_action :set_gasto, only: %i[ show edit update destroy]

  # GET /gastos or /gastos.json
  def index
    @gastos = Gasto.all
  end

  # GET /gastos/1 or /gastos/1.json
  def show
  end

  # GET /gastos/new
  def new
    @gasto = Gasto.new
  end

  # GET /gastos/1/edit
  def edit
  end

  # POST /gastos or /gastos.json
  def create
    @gasto = Gasto.new(gasto_params)

    respond_to do |format|
      if @gasto.save
        format.html { redirect_to gasto_url(@gasto), notice: "Gasto was successfully created." }
        format.json { render :show, status: :created, location: @gasto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gastos/1 or /gastos/1.json
  def update
    respond_to do |format|
      if @gasto.update(gasto_params)
        format.html { redirect_to classificar_path, notice: "Gasto was successfully updated." }
        format.json { render :show, status: :ok, location: @gasto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gastos/1 or /gastos/1.json
  def destroy
    @gasto.destroy!

    respond_to do |format|
      format.html { redirect_to gastos_url, notice: "Gasto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def importfile
    if params[:extrato] != nil
        extrato = params[:extrato]

        doc = File.open(extrato)

        tipo = ""
        data = ""
        valor = ""
        obs = ""

        doc.each do |linha|

          if linha.include? "<TRNTYPE>"
              tipo = linha.strip
              tipo = tipo.delete_prefix "<TRNTYPE>"
              puts tipo
          end

          if linha.include? "<DTPOSTED>"
              data = linha.strip
              data = data.delete_prefix "<DTPOSTED>"
              data = data[6,2]+"/"+data[4,2]+"/"+data[0,4]
              puts data
          end

          if linha.include? "<TRNAMT>"
              valor = linha.strip
              valor = valor.delete_prefix "<TRNAMT>"
              puts valor
          end

          if linha.include? "<MEMO>"
              obs = linha.strip
              obs = obs.delete_prefix "<MEMO>"
              puts obs
          end

          if tipo != "" and data != "" and valor != "" and obs != ""

              @gastos = Gasto.where(data: data).where(valor: valor)

              if @gastos.count == 0
                @g = Gasto.new
                @g.data = Date.parse data
                @g.valor = valor.to_f
                @g.tipogasto_id = 1
                @g.obs = obs
                if !@g.save
                  puts "não salvou"
                end
              end

              tipo = ""
              data = ""
              valor = ""
              obs = ""

          end

        end
    end
  end

  def classificar
    @gastos = Gasto.where(tipogasto_id: 1)
  end

  def consultames
    @tiposd = Tipogasto.where("transacao = 'D'")
    @tiposc = Tipogasto.where("transacao = 'C'")
    @gastos = Gasto.all
    @receitas = Gasto.where("valor > 0")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gasto
      @gasto = Gasto.find(params[:id])
      @tipos = Tipogasto.all
    end

    # Only allow a list of trusted parameters through.
    def gasto_params
      params.require(:gasto).permit(:data, :tipogasto_id, :valor, :obs)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tipogastos_controller.rb
class TipogastosController < ApplicationController
  before_action :set_tipogasto, only: %i[ show edit update destroy ]

  # GET /tipogastos or /tipogastos.json
  def index
    @tipogastos = Tipogasto.all
  end

  # GET /tipogastos/1 or /tipogastos/1.json
  def show
  end

  # GET /tipogastos/new
  def new
    @tipogasto = Tipogasto.new
  end

  # GET /tipogastos/1/edit
  def edit
  end

  # POST /tipogastos or /tipogastos.json
  def create
    @tipogasto = Tipogasto.new(tipogasto_params)

    respond_to do |format|
      if @tipogasto.save
        format.html { redirect_to tipogasto_url(@tipogasto), notice: "Tipogasto was successfully created." }
        format.json { render :show, status: :created, location: @tipogasto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipogasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipogastos/1 or /tipogastos/1.json
  def update
    respond_to do |format|
      if @tipogasto.update(tipogasto_params)
        format.html { redirect_to tipogasto_url(@tipogasto), notice: "Tipogasto was successfully updated." }
        format.json { render :show, status: :ok, location: @tipogasto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipogasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipogastos/1 or /tipogastos/1.json
  def destroy
    @tipogasto.destroy!

    respond_to do |format|
      format.html { redirect_to tipogastos_url, notice: "Tipogasto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipogasto
      @tipogasto = Tipogasto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipogasto_params
      params.require(:tipogasto).permit(:tipo, :transacao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/tipogastos_helper.rb
module TipogastosHelper
end

app/views/gastos/_form.html.erb
<%= form_with(model: gasto) do |form| %>
  <% if gasto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gasto.errors.count, "error") %> prohibited this gasto from being saved:</h2>

      <ul>
        <% gasto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :tipogasto_id, style: "display: block" %>
    <%= form.select :tipogasto_id, Tipogasto.all.map{|t| [t.tipo, t.id]}%>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :obs, style: "display: block" %>
    <%= form.text_field :obs %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gastos/_gasto.html.erb
<div id="<%= dom_id gasto %>">
  <p>
    <strong>Data:</strong>
    <%= gasto.data %>
  </p>

  <p>
    <strong>Tipogasto:</strong>
    <%= gasto.tipogasto.tipo %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= gasto.valor %>
  </p>

  <p>
    <strong>Obs:</strong>
    <%= gasto.obs %>
  </p>

</div>

app/views/gastos/classificar.html.erb
<table class="table table-striped" id="gastos">
  <thead>
    <tr>
      <th>Data</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>Obs</th>
      <th></th>
    </tr>
  </thead>
  <body>
    <% @gastos.each do |gasto| %>
      <%= form_with(model: gasto, ) do |form| %>
        <tr>
          <td>
            <%= form.date_field :data %>
          </td>
          <td>
            <%= form.select :tipogasto_id, Tipogasto.all.map{|t| [t.tipo, t.id]}%>
          </td>
          <td>
            <%= form.text_field :valor, size: 10, align: "right" %>
          </td>
          <td>
            <%= form.text_field :obs, size: 40 %>
          </td>
          <td>
            <%= form.submit %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </body>
</table>

app/views/gastos/consultames.html.erb
<%
  def getValor(mes, tipo)
    valor = 0
    @gastos.each do |g|
      if g.data.month == mes and g.tipogasto == tipo
        valor = valor + g.valor
      end
    end
    return valor
  end

  def getTotalMes(mes, t)
    valor = 0
    @gastos.each do |g|
      if g.data.month == mes and g.tipogasto.transacao == t
        valor = valor + g.valor
      end
    end
    return valor
  end

  ano = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
%>
<table class="table table-striped" id="gastos">
  <thead>
    <tr>
      <th>Tipo/Mes</th>
      <% ano.each do |mes| %>
        <th class="text-center"><%= mes %></th>
      <% end %>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @tiposd.each do |t| %>
      <tr>
        <td><%= t.tipo %></td>
        <% total = 0%>
        <% for mes in 1..12 %>
          <td class="text-end"><%= number_to_currency(getValor(mes,t)) %></td>
          <% total = total + getValor(mes,t) %>
        <% end %>
        <td class="text-end"><%= number_to_currency(total) %></td>
      </tr>
    <% end %>
    <tr>
      <td>Total</td>
      <% for mes in 1..12 %>
        <td class="text-end" ><%= number_to_currency(getTotalMes(mes,"D")) %></td>
      <% end %>
    </tr>
  </tbody>
</table>
<br/>
<table class="table table-striped" id="gastos">
  <thead>
    <tr>
      <th>Tipo/Mes</th>
      <% ano.each do |mes| %>
        <th class="text-center"><%= mes %></th>
      <% end %>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @tiposc.each do |t| %>
      <tr>
        <td><%= t.tipo %></td>
        <% total = 0%>
        <% for mes in 1..12 %>
          <td class="text-end"><%= number_to_currency(getValor(mes,t)) %></td>
          <% total = total + getValor(mes,t) %>
        <% end %>
        <td class="text-end"><%= number_to_currency(total) %></td>
      </tr>
    <% end %>
    <tr>
      <td>Total</td>
      <% for mes in 1 ..12 %>
        <td class="text-end"><%= number_to_currency(getTotalMes(mes,"C")) %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/gastos/edit.html.erb
<h1>Editing gasto</h1>

<%= render "form", gasto: @gasto %>

<br>

<div>
  <%= link_to "Show this gasto", @gasto %> |
  <%= link_to "Back to gastos", gastos_path %>
</div>

app/views/gastos/importfile.html.erb
<br/>


<%= form_with url: "/importfile", multipart: true do |form| %>
  <%= form.file_field :extrato, class: "form-control" %>
  <br/>
  <%= form.submit "importar", class: "btn btn-dark" %>
<% end %>

app/views/gastos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gastos</h1>
<br/>
<%= link_to "New gasto", new_gasto_path, class: "btn btn-dark" %>
<br/>
<br/>
<table class="table table-striped" id="gastos">
  <thead>
    <tr>
      <th>Data</th>
      <th>Valor</th>
      <th>Tipo</th>
    </tr>
  </thead>
  <tbody>
    <% @gastos.each do |gasto| %>
      <tr>
        <td><%= gasto.data %></td>
        <td><%= gasto.valor %></td>
        <td><%= gasto.tipogasto.tipo %></td>
        <td><%= link_to "Edit", edit_gasto_path(gasto) %></td>
        <td><%= link_to "Delete", gasto, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gastos/new.html.erb
<h1>New gasto</h1>

<%= render "form", gasto: @gasto %>

<br>

<div>
  <%= link_to "Back to gastos", gastos_path %>
</div>

app/views/gastos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gasto %>

<div>
  <%= link_to "Edit this gasto", edit_gasto_path(@gasto) %> |
  <%= link_to "Back to gastos", gastos_path %>

  <%= button_to "Destroy this gasto", @gasto, method: :delete %>
</div>

app/views/home/index.html.erb
pagina inicial

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gastos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", media: "all" %>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container-fluid">
        <!-- <a class="navbar-bran" href="#">Navbar</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Home", root_path,  class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Tipo Gasto", tipogastos_path,  class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Gastos
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to "Cadastrar Gastos", gastos_path,  class: "dropdown-item" %></li>
                <li><%= link_to "Importar Gastos", importfile_path,  class: "dropdown-item" %></li>
                <li><%= link_to "Classificar", classificar_path,  class: "dropdown-item" %></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Consulta
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to "Por Mes", consultames_path,  class: "dropdown-item" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>
  <body>
    <div class="container-fluid pt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tipogastos/_form.html.erb
<%= form_with(model: tipogasto) do |form| %>
  <% if tipogasto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tipogasto.errors.count, "error") %> prohibited this tipogasto from being saved:</h2>

      <ul>
        <% tipogasto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>
  <div>
    <%= form.label :transacao, style: "display: block" %>
    <%= form.text_field :transacao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tipogastos/_tipogasto.html.erb
<div id="<%= dom_id tipogasto %>">
  <p>
    <strong>Tipo:</strong>
    <%= tipogasto.tipo %>
  </p>

</div>

app/views/tipogastos/edit.html.erb
<h1>Editing tipogasto</h1>

<%= render "form", tipogasto: @tipogasto %>

<br>

<div>
  <%= link_to "Show this tipogasto", @tipogasto %> |
  <%= link_to "Back to tipogastos", tipogastos_path %>
</div>

app/views/tipogastos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tipo Gastos</h1>
<br/>
  <%= link_to "Novo", new_tipogasto_path,  :class => "btn btn-dark"%>
<br/><br/>

<table class="table table-striped" id="tipogastos">
  <thead>
    <tr>
      <th>Tipo</th>
    </tr>
  </thead>
  <tbody>
    <% @tipogastos.each do |tipogasto| %>
      <tr>
        <td><%= tipogasto.tipo %></td>
        <td><%= link_to "Edit", edit_tipogasto_path(tipogasto) %></td>
        <td><%= link_to "Delete", tipogasto, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tipogastos/new.html.erb
<h1>New tipogasto</h1>

<%= render "form", tipogasto: @tipogasto %>

<br>

<div>
  <%= link_to "Back to tipogastos", tipogastos_path %>
</div>

app/views/tipogastos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tipogasto %>

<div>
  <%= link_to "Edit this tipogasto", edit_tipogasto_path(@tipogasto) %> |
  <%= link_to "Back to tipogastos", tipogastos_path %>

  <%= button_to "Destroy this tipogasto", @tipogasto, method: :delete %>
</div>